### PR TITLE
Game setup

### PR DESCRIPTION
**Pull request by hej2010**

### CODE REVIEW

**Comment by LatteG** [comment]
Why did you comment out this?
`projectileSensorFixtureDef.shape = tempCircle;`
`projectileSensorFixtureDef.density = PROJECTILE_SENSOR_DENSITY;`
`projectileSensorFixtureDef.isSensor = true;`

**Comment by LatteG** [comment]
Why did you comment out the Acceleration multiplier from the Character's move.set?

**Comment by hej2010** [comment]
Got this on the first line
`Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.pottda.game.actorFactory.Box2DActorFactory.fixtureDefInit(Box2DActorFactory.java:279)
	at com.pottda.game.actorFactory.Box2DActorFactory.<init>(Box2DActorFactory.java:67)
	at com.pottda.game.MyGame.create(MyGame.java:85)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)`

**Comment by hej2010** [comment]
And this in Character
`Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.pottda.game.model.Character.giveInput(Character.java:50)
	at com.pottda.game.controller.AbstractController.updateModel(AbstractController.java:49)
	at com.pottda.game.controller.AbstractController.onNewFrame(AbstractController.java:44)
	at com.pottda.game.controller.KeyboardMouseController.onNewFrame(KeyboardMouseController.java:37)
	at com.pottda.game.MyGame.render(MyGame.java:130)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)`

**Comment by LatteG** [comment]
The problem in Character is probably a problem in Inventory, stats not getting their values assigned properly.

No idea about the Box2DActorFactory though... I'll have a proper look tomorrow (or later tonight if I finish the pathfinder at a reasonable time).

Other than that I haven't found anything that needs to be changed.

**Review by EmElw — COMMENTED** [review]
AbstractController.java: is the stage field necessary? if we only use it during the constructor we probably don't need a field for it. 

I'll check the commented parts regarding Item/Inventory/Character when we merge, should be simple enough to fix then

In regards to other parts, I'll evaluate them more properly when merged as it's difficult to grasp exactly what's needed or not, but the loading of stages etc, seems ok.

**Review by EmElw — APPROVED** [review]
Runnable, seems to be working well enough

**Pull request merged**
